services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    env_file:
      - ./.env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.hajd.cloud
      TZ: Europe/Prague
    ports:
      - 3000:3000
    volumes:
      - "./config:/app/config" # Make sure your local config directory exists
      - "./images:/app/public/images"
      - "./icons:/app/public/icons"
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # optional, for docker integrations
      - "/mnt/:/mnt:ro"
    restart: always
