---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks/

- Bookmarks:
    - Homelab:
        - href: https://homelab-fredon.space/ # Either 2 and 4 tab spacing work
          abbr: HO

    - Cloudflare:
        - href: https://cloudflare
          abbr: CD

    - Github:
        - href: https://github.com/patrik-fredon
          abbr: GH

    - YouTube:
        - href: https://youtube.com/
          abbr: YT
    - Reddit:
        - href: https://reddit.com/
          abbr: RD
    - Twitter:
        - href: https://twitter.com/
          abbr: TW
    - Immich:
        - href: https://immich.homelab-fredon.space/
          abbr: IM
    - Proton:
        - href: https://proton.me/
          abbr: PR
    - Perplexity:
        - href: https://perplexity.ai/
          abbr: PX
    - Grok:
        - href: https://grok.com/
          abbr: GR
    - DeepSeek:
        - href: https://deepseek.com/
          abbr: DS
    - Wiki:
        - href: https:/wiki.homelab-fredon.space/
          abbr: WK
    - ITtools:
        - href: https://ittools.tech/
          abbr: IT
    - Beszel:
        - href: https://monbes.homelab-fredon.space/
          abbr: BZ
