---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks/
- Personal:
    - Github:
        - href: https://github.com/patrik-fredon
          icon: github.png
    - YouTube:
        - href: https://youtube.com/
          icon: youtube.png
    - Reddit:
        - href: https://reddit.com/
          icon: reddit.png
    - Twitter:
        - href: https://twitter.com/
          icon: twitter.png
    - Proton:
        - href: https://proton.me/
          icon: proton-mail.png

- Hosting:
    - Wiki:
        - href: https://wiki.homelab-fredon.space/
          icon: wikijs.png
    - Immich:
        - href: https://immich.homelab-fredon.space/
          icon: immich.png
    - Homelab:
        - href: https://homelab-fredon.space/ # Either 2 and 4 tab spacing work
          icon: fredon.png
- AI:
    - Perplexity:
        - href: https://perplexity.ai/
          icon: perplexity.png
    - Grok:
        - href: https://grok.com/
          icon: grok.png
    - DeepSeek:
        - href: https://deepseek.com/
          icon: deepseek.png

- Tools:
    - YAMLValidator:
        - href: https://codebeautify.org/yaml-validator/
          abbr: YM
    - JSONFormatter:
        - href: https://jsonformatter.org/
          abbr: JF
    - ITtools:
        - href: https://ittools.tech/
          abbr: IT
    - Beszel:
        - href: https://monbes.homelab-fredon.space/
          abbr: BZ
    - Cloudflare:
        - href: https://cloudflare.com/
          abbr: CD
