---
- Calendar:
    - Media Calendar:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          maxEvents: 10
          showTime: true
          timezone: Europe/Prague
- Network and IoT:
    - Traefik:
        icon: traefik.svg
        href: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"
        description: Reverse Proxy and Ingress
        widget:
          type: traefik
          url: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"

    - Crowdsec:
        icon: crowdsec.svg
        href: https://app.crowdsec.net
        description: Security
    - Omada:
        icon: omada.svg
        href: https://192.168.0.100
        description: Network Controller
    - Frigate:
        icon: frigate.svg
        href: "{{HOMEPAGE_VAR_FRIGATE_URL}}"
        description: NVR and ML Detection
    - Cloudflare:
        icon: cloudflare.svg
        href: https://dash.cloudflare.com
        description: Public DNS
- Media:
    - Immich:
        icon: immich.svg
        href: "{{HOMEPAGE_VAR_IMMICH_URL}}"
        description: Photos
        widget:
          type: immich
          url: http://192.168.0.115:8760
          key: "{{HOMEPAGE_VAR_IMMICH_API_TOKEN}}"
- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        description: Status Monitor
        widget:
          type: uptimekuma
          url: http://10.43.80.45:3001
          slug: home
    - Speedtest Tracker:
        icon: librespeed.svg
        href: "{{HOMEPAGE_VAR_SPEEDTEST_URL}}"
        description: Internet Speed Test
        widget:
          type: speedtest
          url: http://10.43.1.73:80
