---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Fredon's Homepage
description: “Et in tenebris codicem inveni lucem.” - Fredon

startUrl: https://home.hajd.cloud

layout:
  Calendar:
    style: row
    columns: 3
    tab: "Homelab"
  Management:
    tab: "Homelab"
    style: row
    columns: 3
  Downloads:
    tab: "Homelab"
    style: row
    columns: 3
  Media:
    tab: "Homelab"
    style: row
    columns: 3
  Network:
    tab: "FredonBytes"
    style: row
    columns: 3
  Bookmarks:
    tab: "Bookmarks"
    style: column
    columns: 6

fiveColumns: true
useEqualHeights: true

background:
  image: /images/Banner.jpeg
  blur: sm # sm, md, lg, xl
  saturate: 50 # 0-200 (sytost)
  brightness: 50 # 0-200 (jas)
  opacity: 60

theme: dark
color: gray
cardBlur: md
headerStyle: underlined
favicon: /images/favicon.ico

providers:
  finnhub: cuf975hr01qno7m585ngcuf975hr01qno7m585o0
  openweathermap: 2c694f34ac4dd3eb8e6fad1f16f0ca9c
base: https://home.hajd.cloud

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google # google, duckduckgo, bing, baidu, brave or custom

hideVersion: true
logpath: /logfile/logs
hideTitle: false
showStats: true
target: _blank
statusStyle: dot
maxGroupColumns: 8 # default is 4 for services, 6 for bookmarks, max 8
maxBookmarkGroupColumns: 10 # default is 6, max 8
disableCollapse: true
