---
title: Fredon's Homepage
headerStyle: boxed

showStats: true
showSearch: false
cardBlur: xs
favicon: /images/favicon.png
background:
  image: /images/Banner.jpeg
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 60
theme: dark
color: slate
useEqualHeights: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
hideVersion: true
layout:
  Quick:
    header: false
    style: column
  Dev:
    header: false
    style: column
  Calendar:
    header: false
    style: column
  Network and IoT:
    header: true
    style: row
    columns: 4
  Media:
    header: true
    style: row
    columns: 4
  Monitoring:
    header: true
    style: row
    columns: 4
  Docs:
    header: true
    style: row
    columns: 4
