---
# For configuration options and examples, please see:
# https://gethomepage.dev/widgets/
- logo:
    icon: /images/web-app-manifest-512x512.png

- resources:
    cpu: true
    memory: true
    disk:
      - /
      - /mnt/backup
    expanded: true
    cputemp: true
    tempmin: 0
    tempmax: 80
    uptime: true
    network: true
    diskUnits: bytes
    refresh: 3000
    label: System

- openweathermap:
    label: Brno, CZ
    units: metric
    provider: openweathermap
    cache: 10

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
      timeZone: "Europe/Prague"

# - glances:
# url: http://{{HOMEPAGE_VAR_SERVER_IP}}:61208
# expanded: true
# label: Glances

- stocks:
    provider: finnhub
    watchlist:
      - GME
      - AMC
      - NVDA
      - AMD
      - TSM
      - MSFT
      - AAPL
      - BRK.A
#- search:
#   provider: google
#  focus: false # Auto-focus při načtení
#target: _blank
# showSearchSuggestions: true
