---
# For configuration options and examples, please see:
# https://gethomepage.dev/widgets/

- resources:
    cpu: true
    memory: true
    expanded: true
    refresh: 5000
    label: System

- openweathermap:
    label: Brno, CZ
    units: metric
    provider: openweathermap
    cache: 10

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
      timeZone: "Europe/Prague"
- logo:
    icon: /home/fredon/github/homepage/images/web-app-manifest-512x512.png

# - glances:
# url: http://{{HOMEPAGE_VAR_SERVER_IP}}:61208
# expanded: true
# label: Glances

- stocks:
    provider: finnhub
    watchlist:
      - GME
      - AMC
      - NVDA
      - AMD
      - TSM
      - MSFT
      - AAPL
      - BRK.A

- search:
    provider: google
