- logo:
    icon: /icons/fredon.png
    text_size: 4xl

- greeting:
    text_size: 4xl
    text: fredonbytes.cloud
    href: https://fredonbytes.cloud

- resources:
    expanded: false
    cpu: true
    cputemp: true
    memory: true
    refresh: 1000

- greeting:
    text_size: 4xl
    text: —

- resources:
    label: ARRAY
    expanded: true
    disk:
      - /array

- resources:
    label: MAIN DISK
    expanded: true
    disk:
      - /

- resources:
    label: BACKUP disk
    expanded: true
    disk:
      - /mnt/backup

- greeting:
    text_size: 4xl
    text: —

- resources:
    expanded: true
    uptime: true
    refresh: 1000

- datetime:
    text_size: 4xl
    format:
      timeStyle: short
      hour12: false

- datetime:
    text_size: md
    format:
      dateStyle: long
      hour12: false

- openmeteo:
    label: Brno
    latitude: 0.00
    longitude: 0.00
    timezone: Europe/Prague
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 0
